name: bepicon

channels:
  - conda-forge
  - defaults
  - pytorch
  - nvidia

dependencies:
  - python=3.11
  - pip=23.3.1
  - pytorch=2.5.0
  - pytorch-cuda=11.8
  - pip:
      - graphein==1.7.7
      - h5py==3.10.0
      - MDAnalysis==2.7.0
      - networkx==3.2.1
      - numpy==1.23.5
      - pandas==2.2.3
      - requests==2.32.3
      - scikit-learn==1.4.1.post1
      - torch_geometric==2.6.1
      - torchmetrics==1.4.0.post0
      - tqdm==4.66.2
